### ISSUE TITLE
Having issues making nvim the external editor for godot

### ISSUE THREAD

**Issue by DMunkei** [Lommix/godot.nvim#3]
I'm trying to make godot open neovim when I open the script. Doesn't seem to work for me, followed the steps in the markdown. Any help appreciated.

**Comment by Lommix** [comment]
Godot or the script cannot open nvim for you. You have to start your project in remote mode. The script will then open the file for you. Checkout out the nvim remote docs for further insight:
https://neovim.io/doc/user/remote.html

**Comment by DMunkei** [comment]
Thanks for the hint, I got it working, however I keep getting this error when I try to open a script file from inside of the editor. 
```
➜ /home/x/scripts/open_godot_file.sh: line 4: --: command not found
/home/x/scripts/open_godot_file.sh: line 8: --: command not found
```
That's the script in the readme just named differently.  Not sure what it wants?

**Comment by Lommix** [comment]
it should only have these 3 lines:
```
#!/bin/bash
[ -n "$1" ] && file=$1
nvim --server ~/.cache/nvim/godot.pipe --remote-send ':e '$file'<CR>'
```
did you copy  "--" into your file? These are just meant as file start and end marks.

**Comment by DMunkei** [comment]
Yea, I did. I thought that they were supposed to be that, but because the 1st `--` had the script path I was a bit confused haha.

**Comment by Lommix** [comment]
Updated the docs, to make it more clear.
